
spring:
  application:
    name: sendish-location-importer
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
    properties:
      hibernate:
         cache:
            use_second_level_cache: false
            use_query_cache: false

flyway:
  locations = classpath:db/migrations,classpath:db/migrations/h2

sendish:
  batch:
    country:
      file:
        location: file:///D:/Temp/countryInfo.txt
    city:
      file:
        location: file:///D:/Temp/cities5000.txt

---

spring:
    profiles: prod
