
spring:
  application:
    name: sendish-location-importer
  datasource:
    url: jdbc:h2:file:~/sendish/db
    username: sa
    password: cHusica
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
    properties:
      hibernate:
         cache:
            use_second_level_cache: false
            use_query_cache: false

flyway:
  locations: db/migration,db/h2/migration
  validateOnMigrate: false

sendish:
  batch:
    country:
      file:
        location: file:///D:/Temp/countryInfo.txt
    city:
      file:
        location: file:///D:/Temp/cities5000.txt

---

spring:
    profiles: prod
