spring:
  application:
    name: sendish-batch-app
  datasource:
    url: jdbc:h2:file:~/sendish/db
    username: sa
    password: cHusica
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
    properties:
      hibernate:
         cache:
            use_second_level_cache: false
            use_query_cache: false

flyway:
  locations: db/migration,db/h2/migration
  validateOnMigrate: false

management:
  context-path: /manage
  security:
    role: MANAGE

security:
  enable-csrf: false
  user:
    name: mag
    password: pass

app:
  ios:
    cert:
      dev:
        path: classpath:ios/apns/SendishAPNS_DEV.jks
        pass: sendisH
      prod:
        path: classpath:ios/apns/SendishAPNS_PROD.jks
        pass: sendisH


