spring:
  application:
    name: sendish-location-importer
  datasource:
    url: jdbc:h2:file:~/sendish/db
    username: sa
    password: cHusica
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        generate_statistics: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  social:
    facebook:
      app-id: 364597623699443
      app-secret: ddd32b42d6c5db5386655def6e703f44
  mail:
    host: mail.sendish.com
    port: 587
    username: app.sender@sendish.com
    password: 4fLlmz2qtlDF

management:
  context-path: /manage
  security:
    role: MANAGE

security:
  enable-csrf: false
  user:
    name: mag
    password: pass

endpoints:
  shutdown:
    enabled: true

flyway:
  locations: db/migration,db/h2/migration
  validateOnMigrate: false

app:
  registration:
    mail:
      from: noreply@sendish.com
  baseUrl: http://api.sendish.com
  store:
    data:
      path: C:\Users\chus\sendish\data
  ios:
    cert:
      dev:
        path: classpath:ios/apns/SendishAPNS_DEV.jks
        pass: sendisH
      prod:
        path: classpath:ios/apns/SendishAPNS_PROD.jks
        pass: sendisH

---

spring:
    profiles: prod
