
spring:
  application:
    name: sendish-location-importer
  datasource:
    url: jdbc:h2:mem:sendishdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
    properties:
      hibernate:
         cache:
            use_second_level_cache: true
            use_query_cache: true
            region:
               factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  social:
    facebook:
      app-id: 364597623699443
      app-secret: ddd32b42d6c5db5386655def6e703f44

security:
  enable-csrf: false

flyway:
  locations = classpath:db/migrations,classpath:db/migrations/h2
  
email:
  host: mail.sendish.com
  port: 587
  username: app.sender@sendish.com
  password: 4fLlmz2qtlDF
#  smtp:
#    auth: 
#    starttls:
#      enabled: true

app:
  registration:
    mail:
      from: noreply@sendish.com


---

spring:
    profiles: prod
