
spring:
  application:
    name: sendish-location-importer
  datasource:
    url: jdbc:h2:file:~/sendish/db
    username: sa
    password: cHusica
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
    properties:
      hibernate:
         cache:
            use_second_level_cache: true
            use_query_cache: true
            region:
               factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  social:
    facebook:
      app-id: 364597623699443
      app-secret: ddd32b42d6c5db5386655def6e703f44
  mail:
    host: mail.sendish.com
    port: 587
    username: app.sender@sendish.com
    password: 4fLlmz2qtlDF

security:
  enable-csrf: false

flyway:
  locations = classpath:db/migrations,classpath:db/migrations/h2

app:
  registration:
    mail:
      from: noreply@sendish.com
  baseUrl: http://api.sendish.com
  store:
    data:
      path: C:\Users\janc\sendish\data

---

spring:
    profiles: prod
