spring:
  application:
    name: sendish-api
  datasource:
    url: jdbc:h2:file:~/sendish/db
    username: sa
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        generate_statistics: false
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  social:
    facebook:
      app-id: app_id
      app-secret: app_secret
  mail:
    host: mail.sendish.com
    port: 587
    username: app.sender@sendish.com
    password: some_pass
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  context-path: /manage
  security:
    role: MANAGE

security:
  enable-csrf: false
  user:
    name: mag
    password: pass

endpoints:
  shutdown:
    enabled: false

flyway:
  locations: db/migration,db/h2/migration
  validateOnMigrate: false

app:
  registration:
    mail:
      from: Sendish <noreply@sendish.com>
  baseUrl: http://api.sendish.com
  store:
    data:
      path: C:\Users\janc\sendish\data
  ios:
    cert:
      dev:
        path: classpath:ios/apns/SendishAPNS_DEV.jks
        pass: pass
      prod:
        path: classpath:ios/apns/SendishAPNS_PROD.jks
        pass: pass
  gcm:
    api_key: api_key
  image:
    overlay:
      sendish_logo: classpath:app/image/sendish_64x64.png
  photo:
    hot:
      required_count: 15
      auto_assign: true
